### ISSUE TITLE
mrcz on conda/conda forge

### ISSUE THREAD

**Issue by thomasaarholt** [em-MRCZ/python-mrcz#9]
I think that in order for us to release a new version of hyperspy from conda, we'll need to have mrcz on condaforge as well. Could we upload it there as well as on pip?

**Comment by robbmcleod** [comment]
The conda `meta.yaml` file doesn't like my attempt to include the `futures` module for Python 2.7 only:

https://github.com/em-MRCZ/staged-recipes/blob/master/recipes/mrcz/meta.yaml

https://github.com/conda-forge/staged-recipes/pull/5670

Do you know where the documentation is for these `meta.yaml` recipes?  Because I can't find it.

**Comment by robbmcleod** [comment]
Nevermind they have a bot.

**Comment by robbmcleod** [comment]
It should be available now.

**Comment by thomasaarholt** [comment]
Fantastic, thanks!

**Comment by thomasaarholt** [comment]
I don't think it works yet. At least it's not searchable or installable on conda!

**Comment by robbmcleod** [comment]
@thomasaarholt not sure what happened here, we seem to have fallen through the cracks on conda-forge.

**Comment by robbmcleod** [comment]
Something went wrong with the update for to 0.5.2.

**Comment by robbmcleod** [comment]
Closing as we're generally keeping up with the updates on both PyPi and conda-forge.
